### ISSUE TITLE
You may want to detect shell encoding in your command

### ISSUE THREAD

**Issue by ksamuel** [zacharyvoase/slugify#2]
The bin/slugify command assume the shell encoding is UTF8. It may not always work.

A little detection couldn't hurt:

http://drj11.wordpress.com/2007/05/14/python-how-is-sysstdoutencoding-chosen/

Worst case scenario, you can fall back on UTF8 and add an script option to force the shell encoding.

**Comment by zacharyvoase** [comment]
I just used the value from `sys.stdin.encoding`.
